---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plexautolanguages
  namespace: media
  labels:
    app: plexautolanguages
spec:
  selector:
    matchLabels:
      app: plexautolanguages
  replicas: 1
  template:
    metadata:
      labels:
        app: plexautolanguages
    spec:
      containers:
        - name: plexautolanguages
          image: remirigal/plex-auto-languages:v1.2.1
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              memory: 1Gi
          env:
            - name: TZ
              value: "${TZ}"
            - name: PLEX_URL
              value: http://plex.media:32400
            - name: PLEX_TOKEN
              value: "${SECRET_PLEX_TOKEN}"
