---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pvc.yaml
  - helm-release.yaml
  - volsync.yaml
  - volsync-local.yaml
labels:
  - pairs:
      app.kubernetes.io/name: calibre
      app.kubernetes.io/instance: calibre
