---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: calibre-local-minio-restic
  namespace: media
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: calibre-local-minio-restic-secret
    creationPolicy: Owner
    template:
      metadata:
        annotations:
          replicator.v1.mittwald.de/replicate-to: 'volsync'
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: '{{ .REPOSITORY_TEMPLATE }}/v1-calibre'
        RESTIC_PASSWORD: '{{ .RESTIC_PASSWORD }}'
        AWS_ACCESS_KEY_ID: '{{ .AWS_ACCESS_KEY_ID }}'
        AWS_SECRET_ACCESS_KEY: '{{ .AWS_SECRET_ACCESS_KEY }}'
  dataFrom:
    - extract:
        key: volsync-local-minio-restic-template
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: calibre-local-minio
  namespace: media
spec:
  sourcePVC: calibre-config-0
  trigger:
    schedule: "0 16 * * *"
  restic:
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    copyMethod: Snapshot
    pruneIntervalDays: 10
    repository: calibre-local-minio-restic-secret
    cacheCapacity: 2Gi
    volumeSnapshotClassName: csi-ceph-blockpool
    storageClassName: ceph-block
    cacheStorageClassName: local-path
    retain:
      daily: 10
      within: 10d
